@startuml

' --- SKIN ---

skinparam actorStyle Hollow
left to right direction

' --- DIAGRAMA ---


rectangle UseCase{

    :Estudiante: as E
    :Admin: as A

    rectangle CORE{
        (simularHorarios) as sh
        E --> sh
        sh ..> (buscar\nMateriasXComision)
        (Listar Materias) as lm
        E --> lm
        lm ..> (simular correlativas)
        E --> (listar inscripciones)
        E --> (registrar inscripcion)
        A --> (ABMC de todo)
    }

    rectangle INFO{
        (Resumen Cursada) as rc
        E --> rc
        rc ..> (promedio aprobado)
        rc ..> (porcentaje aprobado)
        E --> (info Materia)
        E --> (info Carrera)
    }
}

rectangle Backend{
    rectangle b[
        <b> Backend
        --
        - regulares: int[]
        - aprobadas: int[]
        - materias: Materia[]
        --
        ==Core==
        + dataInicial(): String[]
        + <b>listarMaterias(): String[][]
        + <b>listarInscripcines(): String[]
        + registrarInscripcion(): void
        + simularHorarios()
        ==InfoResumen==
        + infoMateria(): String[]
        + infoCarrera(): String[]
        + <b>resumenCursada(): String[]
        ==UI==
        + <b>getCarreras()
        + <b>getNiveles()
        + <b>getCondiciones()
        + <b>getNotas()
        + getComisiones()
    ]
}




UseCase -[hidden]up-> Backend

@enduml
