@startuml

' --- SKIN ---

'skinparam actorStyle Hollow
'left to right direction

' --- DIAGRAMA ---




class "VistaInicio" as R
class "VistaMenu" as M{
    -few
}
note left: todas las vistas bajo el Menu tienen boton atras
class "VistaListar" as L <<reusable>>{
    - materiaSeleccionada: int
    --
    + actualizarLista()
    + seleccionarMateria()
}
class "vistaEditarInscripcion" as CI
class "vistaResumenCursada" as RC
class "vistaHorarios" as H
class "vistaInfoCarrera" as IC
class "vistaInfoMateria" as IM
() "Inicio" as I
() "Salir" as X



I .> R
I ..> M

R ..> M
R .> X

M ..> L : Mat
M ..> L : Insc
M ..> IC
M .> X

L ..> RC
L ..> IM
L ..> CI
L ..> H

@enduml
