@startuml

' --- SKIN ---

'skinparam actorStyle Hollow
'left to right direction

' --- DIAGRAMA ---

rectangle UI{
    class "VistaInicio" as R{
        - carreraSeleccionada
    }
    class "VistaMenu" as M{
        - carreraSeleccionada
    }
    note left: todas las vistas bajo el Menu tienen boton atras
    class "VistaListar" as L <<reusable>>{
        - materiaSeleccionada: int
        --
        + actualizarLista()
        + seleccionarMateria()
        + expandirNivel()
        + colapsarNivel()
    }
    class "vistaEditarMateria" as CI{
        - materiaSeleccionada: int
        --
        + aceptar()
        + cancelar()
    }
    class "vistaHorarios" as H
    class "vistaInfoResumen" as IR

    interface "Inicio" as I
    interface "Salir" as X

    I .> R
    I ..> M

    R ..> M
    R .> X

    M ..> L : Mat
    M ..> L : Insc
    M ..> IR : infoC
    M ..> IR : resC
    M ..> H
    M .> X

    L ..> IR: infoM
    L ..> CI
}

@enduml
