@startuml

' --- SKIN ---

skinparam actorStyle Hollow
left to right direction

' --- DIAGRAMA ---

rectangle UTNEZ_UseCase{

    :Estudiante: as E
    :Admin: as A

    rectangle CORE{
        (Listar Materias) as lm
        E --> lm
        lm ..> "<<incl>>" (simular correlativas)
        E --> (listar inscripciones)
        E --> (registrar inscripcion)
        A --> (ABMC de todo)
    }

    rectangle INFO{
        (Resumen Cursada) as rc
        E --> rc
        rc ..> (promedio aprobado)
        rc ..> (porcentaje aprobado)
        E --> (info Materia)
        E --> (info Carrera)
    }
}


@enduml
