@startuml

rectangle Domain{
    annotation GestorInscripcion <<control>>{
        - inscripcionesReg: int[]
        - inscripcionesApDi: int[]
        - materias: Materia[]
        - materiaCursables: int[]
        --
        ==Core==
        + listarInscripcines()
        + <b>registrarInscripcion()
        + editarInscripcion()
        + <b>simularCorrelativas()
        ==Info==
        + resumenCursada()
        + infoCarrera()
        + infoMateria()
        + horariosMateria()
        ==Auxiliar==
        + buscarInscripcionesRegApDi()
        + buscarMaterias()
        + filtrarMateriasDisponibles()
    }

    annotation PantallaInscripcion <<boundary>>{
        - pagMenuPrincipal
        ==Core==
        - pagListaInscripciones
        - pagCrearEditarInscripcion
        - pagMateriasCursables
        ==Info==
        - pagResumenCursada
        - pagInfoCarrera
        - pagInfoMateria
        - pagHorariosMateria
    }

    class Config {
        - nombreAlumno
        - añoIngreso
    }

    class Carrera {
        - nombre
        - descripcion
        --
        + getMaterias()
    }

    class Inscripcion{
        - fecha
    }

    class Materia {
        - numero_orden: int
        - nombre: String
        - descripcion: String
        - modalidad: String
        - sigla: String
        - correlativas_reg: int[]
        - correlativas_ap: int[]
        --
        + esCursable(corReg, corApDi)
    }

    class MateriaXComision{
        --
        + mostrarHorarios()
    }

    class Comision{
        - nombre
    }

    class DiaCursado{}

    enum TipoMateria{
        * Principal
        * Electiva
    }

    enum DiaSemana{
        * Lunes
        * Martes
        * Miercoles
        * Jueves
        * Viernes
        * Sabado
    }

    class Modulo{
        - id
        - horaInicio
        - horaFin
    }

    enum Condicion{
        * Inscripto
        * Aprobado
        * Regular
        * Abandono
    }

    enum Nota{
        * 0 - 10
    }

    enum Especialidad{
        * Civil
        * Electrica
        * Electronica
        * Industrial
        * Mecanica
        * Metalurgica
        * Quimica
        * Sistemas
        * Basica
    }

    enum Turno {
        * Mañaña
        * Tarde
        * Noche
    }

    enum Modalidad {
        * Anual
        * 1C
        * 2C
        * Intensivo
    }

    enum Nivel{
        * 1 - 5
    }

    GestorInscripcion --> Config

    GestorInscripcion <.> PantallaInscripcion



    Carrera *--> Materia
    Carrera --> Especialidad

    Materia --> Especialidad
    Materia --> Nivel
    Materia --> TipoMateria

    Inscripcion --> MateriaXComision
    Inscripcion --> Condicion
    Inscripcion --> Nota

    MateriaXComision --> Materia
    MateriaXComision --> Comision
    MateriaXComision *--> DiaCursado : horarios
    MateriaXComision --> Modalidad

    DiaCursado --> DiaSemana
    DiaCursado *--> Modulo

    Comision --> Turno
    Comision --> Especialidad
    Comision --> Nivel
}

rectangle Presentacion{
    class PresEspecialidad{
        - id
        - letra
        - icono
    }

    class PresCondicion{
        - id
        - colorFondo
    }

    class PresTipoMateria{
        - id
        - icono
    }
}

@enduml

