@startuml

' --- SKIN ---

skinparam actorStyle Hollow
hide footbox

' --- DIAGRAMA ---

actor Steve as A
boundary Pantalla as P
control Gestor as G
entity Inscripcion as I
entity Materia as M

A -> P : opcionRegInscripcion()
P -> P : pedirCondicion()
A -> P : tomarCondicion()
P -> P : pedirNota()
A -> P : tomarNota()
P -> G : registrarInscripcion()

loop hasta encontrar materia con orden
    G -> I : esOrdenMateria()
    I -> M : esOrdenMateria()
end

create entity nuevaInscripcion as N
G -> N : new(materiaComision, fecha, condicion, nota)

@enduml
