@startuml

' --- SKIN ---

skinparam actorStyle Hollow
hide footbox

' --- DIAGRAMA ---

title "Simular Correlativas"

actor CUListarMaterias as CU
control Gestor as G
entity Inscripcion as I
entity Carrera as C
entity Materia as M

CU --> G : simular()
G -> G : buscarInscripcionesRegApDi()

loop todas las incripciones
    G -> I : esRegular()
    G -> I : getOrden()
    I -> M : getOrden()

    G -> I : esAprobada()
    G -> I : getOrden()
    I -> M : getOrden()
end

G -> G : buscarMaterias()
G -> C : geMaterias()
G -> G : filtrarMateriasDisponibles()

loop todas las materias
    G -> M : esCursable()
    G -> M : getOrden()
end

@enduml
